# Generated by Django 2.0.4 on 2018-04-14 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=4096)),
            ],
            options={
                'verbose_name': 'תשובה',
                'verbose_name_plural': 'תשובות',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='כתובת אינטרנט')),
                ('views', models.IntegerField(default=0, verbose_name='צפיות')),
                ('answers', models.IntegerField(default=0, verbose_name='תשובות')),
                ('contentType', models.CharField(max_length=500)),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
            options={
                'verbose_name': 'מסמך',
                'verbose_name_plural': 'מסמכים',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='שם')),
            ],
            options={
                'verbose_name': 'פרויקט',
                'verbose_name_plural': 'פרויקטים',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=50, verbose_name='shortname')),
                ('question_text', models.CharField(max_length=200, verbose_name='question_text')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
                ('order', models.IntegerField(default=0, verbose_name='סודר')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorslaves.Project', verbose_name='פרויקט')),
            ],
            options={
                'verbose_name': 'שאלה',
                'verbose_name_plural': 'שאלות',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorslaves.Project', verbose_name='פרויקט'),
        ),
        migrations.AddField(
            model_name='answer',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poorslaves.Document', verbose_name='מסמך'),
        ),
    ]
