# Generated by Django 2.0.4 on 2018-04-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorslaves', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='short',
            new_name='shortname',
        ),
    ]
