# Generated by Django 2.0.4 on 2018-05-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorslaves', '0002_auto_20180414_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='height',
        ),
        migrations.RemoveField(
            model_name='document',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
        migrations.RemoveField(
            model_name='document',
            name='size',
        ),
        migrations.RemoveField(
            model_name='document',
            name='width',
        ),
        migrations.RemoveField(
            model_name='question',
            name='project',
        ),
        migrations.AlterField(
            model_name='question',
            name='shortname',
            field=models.CharField(help_text='question shortname', max_length=50, verbose_name='shortname'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
