# Generated by Django 2.0.4 on 2018-05-12 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poorslaves', '0003_auto_20180512_2231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
