# Generated by Django 2.0.4 on 2018-05-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorslaves', '0004_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='metadata',
            field=models.CharField(default='', max_length=500, verbose_name='metadata'),
            preserve_default=False,
        ),
    ]
