# Generated by Django 2.0.4 on 2018-07-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorslaves', '0005_document_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='accepted',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
