# Generated by Django 2.0.4 on 2018-11-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poorslaves', '0006_auto_20180726_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_shown',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
